version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: api
    container_name: api
    environment:
      - config=config
    ports:
      - "3000:3000"

  postgres:
    image: postgres:17-alpine
    container_name: postgres_eff
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eff_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path=/migrations", "-database=postgres://postgres:postgres@postgres:5432/eff_db?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: