server:
  AppEnv: development
  Port: :3000
  ReadTimeout: 10
  WriteTimeout: 10
postgres:
  PostgresqlHost: postgres
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: eff_db
  PostgresqlSSLMode: disable
  PgDriver: pgx