basePath: /
definitions:
  models.CostDetail:
    properties:
      active_months:
        type: integer
      cost:
        type: integer
      id:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  models.CostResponse:
    properties:
      details:
        items:
          $ref: '#/definitions/models.CostDetail'
        type: array
      total_cost:
        type: integer
    type: object
  models.CreateSubscriptionRequest:
    properties:
      end_date:
        type: string
      name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      user_id:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.PaginatedResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.SubscriptionResponse'
        type: array
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  models.SubscriptionResponse:
    properties:
      created_at:
        type: string
      end_date:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  models.UpdateSubscriptionRequest:
    properties:
      end_date:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: API для управления подписками пользователей
  title: Subscription API
  version: "1.0"
paths:
  /subscriptions:
    get:
      description: Возвращает список подписок с пагинацией
      parameters:
      - default: 1
        description: Номер страницы (по умолчанию 1)
        in: query
        name: page
        type: integer
      - default: 10
        description: Размер страницы (по умолчанию 10)
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginatedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Список подписок
      tags:
      - subscriptions CRUDL
    post:
      consumes:
      - application/json
      description: Создаёт новую запись о подписке пользователя
      parameters:
      - description: Данные подписки
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Создать подписку
      tags:
      - subscriptions CRUDL
  /subscriptions/{id}:
    delete:
      description: Удаляет подписку по её идентификатору
      parameters:
      - description: UUID подписки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Удалить подписку
      tags:
      - subscriptions CRUDL
    get:
      description: Возвращает подписку по её идентификатору
      parameters:
      - description: UUID подписки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Получить подписку по ID
      tags:
      - subscriptions CRUDL
    put:
      consumes:
      - application/json
      description: Обновляет название, стоимость и дату окончания подписки
      parameters:
      - description: UUID подписки
        in: path
        name: id
        required: true
        type: string
      - description: Новые данные
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Обновить подписку
      tags:
      - subscriptions CRUDL
  /subscriptions/cost:
    get:
      description: Считает суммарную стоимость подписок за указанный период
      parameters:
      - description: Начало (YYYY-MM-DD)
        in: query
        name: period_start
        required: true
        type: string
      - description: Конец (YYYY-MM-DD)
        in: query
        name: period_end
        required: true
        type: string
      - description: Фильтр по ID пользователя
        in: query
        name: user_id
        type: string
      - description: Фильтр по названию
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Стоимость подписок за период
      tags:
      - subscriptions COST
swagger: "2.0"
